### ISSUE TITLE
srr cannot work with generator-umi@4.6.0

### ISSUE THREAD

**Issue by DingWill** [DFocusGroup/generator-umi#8]
## 问题
`yo umi`创建项目后，`yarn start`启动正常，`yarn build`正常。

当在config目录下的 `config.ts` 添加`ssr`，再`start` 或者 `build`都会报错。

`config.ts`文件：
![1](https://user-images.githubusercontent.com/11881200/110625010-dff20a80-81d9-11eb-801f-dca65660a455.png)

报错信息：
```
Cannot find module 'serialize-javascript'
Error: Cannot find module 'serialize-javascript'
```

## 环境
node版本：`14.16.0`
generator-umi：`4.6.0`

**Comment by leftstick** [comment]
I just checked the code, this generator doesn't support SSR. 

You should create from scratch by your own via `@umijs/umi-app`
